export default {
  state: {
    menuList: [
      {
        id: 'w_001',
        pid: '0',
        name: '招聘管理',
        url: null,
        type: 0,
        icon: 'icon-set',
        permissions: null,
        sort: 0,
        createDate: '2019-02-13 22:02:39',
        parentName: null,
        children: [{
          id: 'w_001_01',
          pid: 'w_001',
          name: '职位管理',
          url: 'rec/user',
          type: 0,
          icon: 'icon-user',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        }, {
          id: 'w_001_02',
          pid: 'w_001',
          name: '岗位需求',
          url: 'rec/menu',
          type: 0,
          icon: 'icon-menu',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        }, {
          id: 'w_001_03',
          pid: 'w_001',
          name: '简历管理',
          url: 'rec/role',
          type: 0,
          icon: 'icon-role',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        }, {
          id: 'w_001_04',
          pid: 'w_001',
          name: '面试管理',
          url: 'rec/dept',
          type: 0,
          icon: 'icon-dept',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        },
        {
          id: 'w_001_05',
          pid: 'w_001',
          name: '入职通知',
          url: 'rec/tongzhi',
          type: 0,
          icon: 'icon-dept',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        }]
      },
      // 人事关系
      {
        id: 'w_002',
        pid: '0',
        name: '人事关系',
        url: null,
        type: 0,
        icon: 'icon-set',
        permissions: null,
        sort: 0,
        createDate: '2019-02-13 22:02:39',
        parentName: null,
        children: [{
          id: 'w_002_01',
          pid: 'w_002',
          name: '劳务合同签署',
          url: 'per/user',
          type: 0,
          icon: 'icon-user',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        }, {
          id: 'w_002_02',
          pid: 'w_002',
          name: '员工入职',
          url: 'per/menu',
          type: 0,
          icon: 'icon-menu',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        }, {
          id: 'w_002_03',
          pid: 'w_002',
          name: '员工转正',
          url: 'per/role',
          type: 0,
          icon: 'icon-role',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        }, {
          id: 'w_002_04',
          pid: 'w_002',
          name: '员工调岗',
          url: 'per/dept',
          type: 0,
          icon: 'icon-dept',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        },
        {
          id: 'w_002_05',
          pid: 'w_002',
          name: '员工离职',
          url: 'per/tongzhi',
          type: 0,
          icon: 'icon-dept',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        }]
      },
      // 员工档案
      {
        id: 'w_003',
        pid: '0',
        name: '员工档案',
        url: null,
        type: 0,
        icon: 'icon-set',
        permissions: null,
        sort: 0,
        createDate: '2019-02-13 22:02:39',
        parentName: null,
        children: [{
          id: 'w_003_01',
          pid: 'w_003',
          name: '员工台账',
          url: 'per/user',
          type: 0,
          icon: 'icon-user',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        }, {
          id: 'w_003_02',
          pid: 'w_003',
          name: '我的卡片',
          url: 'per/menu',
          type: 0,
          icon: 'icon-menu',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        }, {
          id: 'w_002_03',
          pid: 'w_002',
          name: '我的下属',
          url: 'per/role',
          type: 0,
          icon: 'icon-role',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        }]
      },
      // 考勤管理
      {
        id: 'w_004',
        pid: '0',
        name: '考勤管理',
        url: null,
        type: 0,
        icon: 'icon-set',
        permissions: null,
        sort: 0,
        createDate: '2019-02-13 22:02:39',
        parentName: null,
        children: [{
          id: 'w_004_01',
          pid: 'w_004',
          name: '员工台账',
          url: 'per/user',
          type: 0,
          icon: 'icon-user',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        }, {
          id: 'w_004_02',
          pid: 'w_004',
          name: '我的卡片',
          url: 'per/menu',
          type: 0,
          icon: 'icon-menu',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        }, {
          id: 'w_004_03',
          pid: 'w_004',
          name: '我的下属',
          url: 'per/role',
          type: 0,
          icon: 'icon-role',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        }]
      },
      // 绩效管理
      {
        id: 'w_005',
        pid: '0',
        name: '绩效管理',
        url: null,
        type: 0,
        icon: 'icon-set',
        permissions: null,
        sort: 0,
        createDate: '2019-02-13 22:02:39',
        parentName: null,
        children: [{
          id: 'w_005_01',
          pid: 'w_005',
          name: '员工台账',
          url: 'per/user',
          type: 0,
          icon: 'icon-user',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        }, {
          id: 'w_005_02',
          pid: 'w_005',
          name: '我的卡片',
          url: 'per/menu',
          type: 0,
          icon: 'icon-menu',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        }, {
          id: 'w_005_03',
          pid: 'w_004',
          name: '我的下属',
          url: 'per/role',
          type: 0,
          icon: 'icon-role',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        }]
      },
      // 项目管理
      {
        id: 'w_006',
        pid: '0',
        name: '项目管理',
        url: null,
        type: 0,
        icon: 'icon-set',
        permissions: null,
        sort: 0,
        createDate: '2019-02-13 22:02:39',
        parentName: null,
        children: [{
          id: 'w_006_01',
          pid: 'w_006',
          name: '员工台账',
          url: 'per/user',
          type: 0,
          icon: 'icon-user',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        }, {
          id: 'w_006_02',
          pid: 'w_006',
          name: '我的卡片',
          url: 'per/menu',
          type: 0,
          icon: 'icon-menu',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        }, {
          id: 'w_006_03',
          pid: 'w_006',
          name: '我的下属',
          url: 'per/role',
          type: 0,
          icon: 'icon-role',
          permissions: null,
          sort: 0,
          createDate: '2019-02-13 22:02:39',
          parentName: null,
          children: []
        }]
      }
    ]
  }
}
